### ISSUE TITLE
ImportError: No module named cloudflare.main

### ISSUE THREAD

**Issue by pastephens** [darylyu/cloudflare-python#2]
✘ stephens1@seclnxvdi10  ~/cloudflare-python   master  sudo python setup.py install
running install
running bdist_egg
running egg_info
creating cloudflare.egg-info
writing requirements to cloudflare.egg-info/requires.txt
writing cloudflare.egg-info/PKG-INFO
writing top-level names to cloudflare.egg-info/top_level.txt
writing dependency_links to cloudflare.egg-info/dependency_links.txt
writing entry points to cloudflare.egg-info/entry_points.txt
writing manifest file 'cloudflare.egg-info/SOURCES.txt'
reading manifest file 'cloudflare.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
writing manifest file 'cloudflare.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/cloudflare
copying cloudflare/__init__.py -> build/lib/cloudflare
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/cloudflare
copying build/lib/cloudflare/__init__.py -> build/bdist.linux-x86_64/egg/cloudflare
byte-compiling build/bdist.linux-x86_64/egg/cloudflare/__init__.py to __init__.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying cloudflare.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cloudflare.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cloudflare.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cloudflare.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cloudflare.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cloudflare.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cloudflare.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/cloudflare-0.0.1-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing cloudflare-0.0.1-py2.7.egg
creating /usr/lib/python2.7/site-packages/cloudflare-0.0.1-py2.7.egg
Extracting cloudflare-0.0.1-py2.7.egg to /usr/lib/python2.7/site-packages
Adding cloudflare 0.0.1 to easy-install.pth file
Installing cloudflare script to /usr/bin

Installed /usr/lib/python2.7/site-packages/cloudflare-0.0.1-py2.7.egg
Processing dependencies for cloudflare==0.0.1
Searching for click>=4.0
Reading https://pypi.python.org/simple/click/
Best match: click 6.2
Downloading https://pypi.python.org/packages/source/c/click/click-6.2.tar.gz#md5=83252a8095397b1f5f710fdd58b484d9
Processing click-6.2.tar.gz
Writing /tmp/easy_install-9Ryu96/click-6.2/setup.cfg
Running click-6.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-9Ryu96/click-6.2/egg-dist-tmp-alnt80
warning: no previously-included files matching '*.pyc' found under directory 'docs'
warning: no previously-included files matching '*.pyo' found under directory 'docs'
warning: no previously-included files matching '*.pyc' found under directory 'tests'
warning: no previously-included files matching '*.pyo' found under directory 'tests'
warning: no previously-included files matching '*.pyc' found under directory 'examples'
warning: no previously-included files matching '*.pyo' found under directory 'examples'
no previously-included directories found matching 'docs/_build'
zip_safe flag not set; analyzing archive contents...

  1 ---
click.core: module references __file__
creating /usr/lib/python2.7/site-packages/click-6.2-py2.7.egg
Extracting click-6.2-py2.7.egg to /usr/lib/python2.7/site-packages
Adding click 6.2 to easy-install.pth file

Installed /usr/lib/python2.7/site-packages/click-6.2-py2.7.egg
Searching for requests==2.7.0
Best match: requests 2.7.0
Adding requests 2.7.0 to easy-install.pth file

Using /usr/lib/python2.7/site-packages
Searching for urllib3==1.10.4
Best match: urllib3 1.10.4
Adding urllib3 1.10.4 to easy-install.pth file

Using /usr/lib/python2.7/site-packages
Finished processing dependencies for cloudflare==0.0.1
 stephens1@seclnxvdi10  ~/cloudflare-python   master  cd
 stephens1@seclnxvdi10  ~  /usr/bin/cloudflare cnofig
Traceback (most recent call last):
  File "/usr/bin/cloudflare", line 9, in <module>
    load_entry_point('cloudflare==0.0.1', 'console_scripts', 'cloudflare')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named cloudflare.main
 ✘ stephens1@seclnxvdi10  ~  /usr/bin/cloudflare config
Traceback (most recent call last):
  File "/usr/bin/cloudflare", line 9, in <module>
    load_entry_point('cloudflare==0.0.1', 'console_scripts', 'cloudflare')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named cloudflare.main

**Comment by darylyu** [comment]
@pastephens Thanks for bringing this up. I'll try to make time for this during the holidays.
